seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: CNN
    clip_actions: True
    clip_log_std: True
    min_log_std: -20
    max_log_std: 0.5
    reduction: sum
    grid_side: 20
    other_obs_size: 20
    # network:
    #   - name: net
    #     input: STATES
    #     layers: [128, 128]
    #     activations: elu
    # output: ACTIONS
  value:  # see deterministic_model parameters
    # class: CNNValue
    # clip_actions: False
    # grid_is_dynamic: True
    # grid_side: 10
    # grid_embed_dim: 16
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [128, 128]
        activations: elu
    output: ONE


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# PPO agent configuration (field names are from PPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  class: PPO
  rollouts: 10
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: KLAaptiveLR
  learning_rate_scheduler: null
  learning_rate: 3.0e-4
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
  state_preprocessor: null
  state_preprocessor_kwargs: null
  value_preprocessor: null
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.01
  value_loss_scale: 0.5
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: "car_navigation"
    experiment_name: ""
    write_interval: 1
    checkpoint_interval: 1000

    wandb: True
    wandb_kwargs: {
      project: "tdmpc2",
      entity: "chja_jiangxin-huazhong-university-of-science-and-technology",
      mode: "online",
      sync_tensorboard: True

    }


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 100000
  environment_info: log
